# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(733, 226)
        self.gridLayout_4 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(11, 11, 651, 121))
        self.widget.setObjectName("widget")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_18.addWidget(self.label, 0, 0, 1, 6)
        self.pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setCheckable(False)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_18.addWidget(self.pushButton_1, 1, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_18.addWidget(self.pushButton_2, 1, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_18.addWidget(self.pushButton_3, 1, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setCheckable(False)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_18.addWidget(self.pushButton_4, 1, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_18.addWidget(self.pushButton_5, 1, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_18.addWidget(self.pushButton, 1, 5, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(12, 12, 407, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setEnabled(True)
        self.pushButton_11.setGeometry(QtCore.QRect(13, 51, 93, 89))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Pic/a4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_11.setCheckable(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_9.setGeometry(QtCore.QRect(513, 51, 91, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setEnabled(True)
        self.pushButton_10.setGeometry(QtCore.QRect(313, 51, 93, 89))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Pic/r1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon1)
        self.pushButton_10.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_10.setCheckable(False)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setEnabled(True)
        self.pushButton_8.setGeometry(QtCore.QRect(113, 51, 93, 89))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Pic/a3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon2)
        self.pushButton_8.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_8.setCheckable(False)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setEnabled(True)
        self.pushButton_7.setGeometry(QtCore.QRect(213, 51, 93, 89))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Pic/s1t.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_7.setCheckable(False)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_6.setEnabled(True)
        self.pushButton_6.setGeometry(QtCore.QRect(413, 51, 93, 89))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Pic/v1i.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon4)
        self.pushButton_6.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_6.setCheckable(False)
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.widget1 = QtWidgets.QWidget(self.tab_3)
        self.widget1.setGeometry(QtCore.QRect(11, 1, 561, 141))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_36 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_36.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Pic/f1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_36.setIcon(icon5)
        self.pushButton_36.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_36.setCheckable(False)
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_3.addWidget(self.pushButton_36, 1, 0, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_39.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_39.sizePolicy().hasHeightForWidth())
        self.pushButton_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("Pic/f2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_39.setIcon(icon6)
        self.pushButton_39.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_39.setCheckable(False)
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout_3.addWidget(self.pushButton_39, 1, 1, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_38.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("Pic/f3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_38.setIcon(icon7)
        self.pushButton_38.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_38.setCheckable(False)
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_3.addWidget(self.pushButton_38, 1, 2, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_40.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_40.sizePolicy().hasHeightForWidth())
        self.pushButton_40.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Pic/f4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_40.setIcon(icon8)
        self.pushButton_40.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_40.setCheckable(False)
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout_3.addWidget(self.pushButton_40, 1, 3, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        self.label_6.setGeometry(QtCore.QRect(12, 12, 391, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_30.setEnabled(True)
        self.pushButton_30.setGeometry(QtCore.QRect(13, 51, 93, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setCheckable(False)
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_35 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_35.setGeometry(QtCore.QRect(513, 51, 93, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_31 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_31.setEnabled(True)
        self.pushButton_31.setGeometry(QtCore.QRect(413, 51, 93, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setCheckable(False)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_34 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_34.setEnabled(True)
        self.pushButton_34.setGeometry(QtCore.QRect(313, 51, 93, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setCheckable(False)
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_33 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_33.setEnabled(True)
        self.pushButton_33.setGeometry(QtCore.QRect(113, 51, 93, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setCheckable(False)
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_32 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_32.setEnabled(True)
        self.pushButton_32.setGeometry(QtCore.QRect(213, 51, 93, 86))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setCheckable(False)
        self.pushButton_32.setObjectName("pushButton_32")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.layoutWidget = QtWidgets.QWidget(self.tab_5)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 661, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_42 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_42.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_42.sizePolicy().hasHeightForWidth())
        self.pushButton_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("Pic/w1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_42.setIcon(icon9)
        self.pushButton_42.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_42.setCheckable(False)
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout_2.addWidget(self.pushButton_42, 1, 0, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_43.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_43.sizePolicy().hasHeightForWidth())
        self.pushButton_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Pic/w5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_43.setIcon(icon10)
        self.pushButton_43.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_43.setCheckable(False)
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout_2.addWidget(self.pushButton_43, 1, 4, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_44.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_44.sizePolicy().hasHeightForWidth())
        self.pushButton_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("Pic/w3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_44.setIcon(icon11)
        self.pushButton_44.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_44.setCheckable(False)
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout_2.addWidget(self.pushButton_44, 1, 2, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_45.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_45.sizePolicy().hasHeightForWidth())
        self.pushButton_45.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("Pic/w2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_45.setIcon(icon12)
        self.pushButton_45.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_45.setCheckable(False)
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout_2.addWidget(self.pushButton_45, 1, 1, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_46.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_46.sizePolicy().hasHeightForWidth())
        self.pushButton_46.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("Pic/w4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_46.setIcon(icon13)
        self.pushButton_46.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_46.setCheckable(False)
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout_2.addWidget(self.pushButton_46, 1, 3, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_47.sizePolicy().hasHeightForWidth())
        self.pushButton_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("Pic/w6.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_47.setIcon(icon14)
        self.pushButton_47.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout_2.addWidget(self.pushButton_47, 1, 5, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_6)
        self.layoutWidget_3.setGeometry(QtCore.QRect(0, 0, 651, 151))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_54 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_54.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_54.sizePolicy().hasHeightForWidth())
        self.pushButton_54.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("Pic/tt1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_54.setIcon(icon15)
        self.pushButton_54.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_54.setCheckable(False)
        self.pushButton_54.setObjectName("pushButton_54")
        self.gridLayout_6.addWidget(self.pushButton_54, 1, 0, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_55.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_55.sizePolicy().hasHeightForWidth())
        self.pushButton_55.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("Pic/tt5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_55.setIcon(icon16)
        self.pushButton_55.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_55.setCheckable(False)
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout_6.addWidget(self.pushButton_55, 1, 4, 1, 1)
        self.pushButton_56 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_56.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_56.sizePolicy().hasHeightForWidth())
        self.pushButton_56.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("Pic/tt3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_56.setIcon(icon17)
        self.pushButton_56.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_56.setCheckable(False)
        self.pushButton_56.setObjectName("pushButton_56")
        self.gridLayout_6.addWidget(self.pushButton_56, 1, 2, 1, 1)
        self.pushButton_57 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_57.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_57.sizePolicy().hasHeightForWidth())
        self.pushButton_57.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("Pic/tt2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_57.setIcon(icon18)
        self.pushButton_57.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_57.setCheckable(False)
        self.pushButton_57.setObjectName("pushButton_57")
        self.gridLayout_6.addWidget(self.pushButton_57, 1, 1, 1, 1)
        self.pushButton_58 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_58.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_58.sizePolicy().hasHeightForWidth())
        self.pushButton_58.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("Pic/tt4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_58.setIcon(icon19)
        self.pushButton_58.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_58.setCheckable(False)
        self.pushButton_58.setObjectName("pushButton_58")
        self.gridLayout_6.addWidget(self.pushButton_58, 1, 3, 1, 1)
        self.pushButton_59 = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_59.sizePolicy().hasHeightForWidth())
        self.pushButton_59.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("Pic/tt6.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_59.setIcon(icon20)
        self.pushButton_59.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_59.setObjectName("pushButton_59")
        self.gridLayout_6.addWidget(self.pushButton_59, 1, 5, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_15 = QtWidgets.QWidget()
        self.tab_15.setObjectName("tab_15")
        self.widget2 = QtWidgets.QWidget(self.tab_15)
        self.widget2.setGeometry(QtCore.QRect(4, 1, 651, 151))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_27 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.pushButton_150 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_150.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_150.sizePolicy().hasHeightForWidth())
        self.pushButton_150.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_150.setFont(font)
        self.pushButton_150.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("Pic/t1.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_150.setIcon(icon21)
        self.pushButton_150.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_150.setCheckable(False)
        self.pushButton_150.setObjectName("pushButton_150")
        self.gridLayout_17.addWidget(self.pushButton_150, 1, 0, 1, 1)
        self.pushButton_151 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_151.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_151.sizePolicy().hasHeightForWidth())
        self.pushButton_151.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_151.setFont(font)
        self.pushButton_151.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("Pic/t5.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_151.setIcon(icon22)
        self.pushButton_151.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_151.setCheckable(False)
        self.pushButton_151.setObjectName("pushButton_151")
        self.gridLayout_17.addWidget(self.pushButton_151, 1, 4, 1, 1)
        self.pushButton_152 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_152.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_152.sizePolicy().hasHeightForWidth())
        self.pushButton_152.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_152.setFont(font)
        self.pushButton_152.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("Pic/t3.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_152.setIcon(icon23)
        self.pushButton_152.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_152.setCheckable(False)
        self.pushButton_152.setObjectName("pushButton_152")
        self.gridLayout_17.addWidget(self.pushButton_152, 1, 2, 1, 1)
        self.pushButton_153 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_153.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_153.sizePolicy().hasHeightForWidth())
        self.pushButton_153.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_153.setFont(font)
        self.pushButton_153.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("Pic/t2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_153.setIcon(icon24)
        self.pushButton_153.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_153.setCheckable(False)
        self.pushButton_153.setObjectName("pushButton_153")
        self.gridLayout_17.addWidget(self.pushButton_153, 1, 1, 1, 1)
        self.pushButton_154 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_154.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_154.sizePolicy().hasHeightForWidth())
        self.pushButton_154.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_154.setFont(font)
        self.pushButton_154.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("Pic/t4.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_154.setIcon(icon25)
        self.pushButton_154.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_154.setCheckable(False)
        self.pushButton_154.setObjectName("pushButton_154")
        self.gridLayout_17.addWidget(self.pushButton_154, 1, 3, 1, 1)
        self.pushButton_155 = QtWidgets.QPushButton(self.widget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_155.sizePolicy().hasHeightForWidth())
        self.pushButton_155.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_155.setFont(font)
        self.pushButton_155.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("Pic/t6.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_155.setIcon(icon26)
        self.pushButton_155.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_155.setObjectName("pushButton_155")
        self.gridLayout_17.addWidget(self.pushButton_155, 1, 5, 1, 1)
        self.verticalLayout_10.addLayout(self.gridLayout_17)
        self.tabWidget.addTab(self.tab_15, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_7)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 621, 141))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_48 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_48.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_48.sizePolicy().hasHeightForWidth())
        self.pushButton_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setCheckable(False)
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout_5.addWidget(self.pushButton_48, 1, 0, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_49.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setCheckable(False)
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout_5.addWidget(self.pushButton_49, 1, 4, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_50.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_50.sizePolicy().hasHeightForWidth())
        self.pushButton_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setCheckable(False)
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout_5.addWidget(self.pushButton_50, 1, 2, 1, 1)
        self.pushButton_51 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_51.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_51.sizePolicy().hasHeightForWidth())
        self.pushButton_51.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setCheckable(False)
        self.pushButton_51.setObjectName("pushButton_51")
        self.gridLayout_5.addWidget(self.pushButton_51, 1, 1, 1, 1)
        self.pushButton_52 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_52.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_52.sizePolicy().hasHeightForWidth())
        self.pushButton_52.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setCheckable(False)
        self.pushButton_52.setObjectName("pushButton_52")
        self.gridLayout_5.addWidget(self.pushButton_52, 1, 3, 1, 1)
        self.pushButton_53 = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(7)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_53.sizePolicy().hasHeightForWidth())
        self.pushButton_53.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(48)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setObjectName("pushButton_53")
        self.gridLayout_5.addWidget(self.pushButton_53, 1, 5, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.tabWidget.addTab(self.tab_7, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.tabWidget.raise_()
        self.label_3.raise_()

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_2.pressed.connect(self.tabWidget.showFullScreen)
        self.pushButton_8.clicked.connect(self.tabWidget.show)
        self.pushButton_36.clicked.connect(self.tabWidget.show)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.pushButton_1)
        Dialog.setTabOrder(self.pushButton_1, self.pushButton_2)
        Dialog.setTabOrder(self.pushButton_2, self.pushButton_3)
        Dialog.setTabOrder(self.pushButton_3, self.pushButton_4)
        Dialog.setTabOrder(self.pushButton_4, self.pushButton_5)
        Dialog.setTabOrder(self.pushButton_5, self.pushButton)
        Dialog.setTabOrder(self.pushButton, self.pushButton_11)
        Dialog.setTabOrder(self.pushButton_11, self.pushButton_8)
        Dialog.setTabOrder(self.pushButton_8, self.pushButton_7)
        Dialog.setTabOrder(self.pushButton_7, self.pushButton_10)
        Dialog.setTabOrder(self.pushButton_10, self.pushButton_6)
        Dialog.setTabOrder(self.pushButton_6, self.pushButton_9)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Идентификация ЛА"))
        self.label_3.setText(_translate("Dialog", "Вывод"))
        self.label.setText(_translate("Dialog", "Выберите направление движения объекта по отношению к ВАМ"))
        self.pushButton_1.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.pushButton_1.setText(_translate("Dialog", "↙"))
        self.pushButton_2.setText(_translate("Dialog", "↘"))
        self.pushButton_3.setText(_translate("Dialog", "↓"))
        self.pushButton_4.setText(_translate("Dialog", "↖"))
        self.pushButton_5.setText(_translate("Dialog", "↗"))
        self.pushButton.setText(_translate("Dialog", "↑"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Напр."))
        self.label_2.setText(_translate("Dialog", "              Выберите форму объекта"))
        self.pushButton_11.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.pushButton_9.setText(_translate("Dialog", "Вернуться \n"
"  назад"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Силуэт"))
        self.label_7.setText(_translate("Dialog", "Выберите форму планера по подклассам"))
        self.pushButton_36.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Форма"))
        self.label_6.setText(_translate("Dialog", "Сколько двигателей на ваш взгляд"))
        self.pushButton_30.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.pushButton_30.setText(_translate("Dialog", "1"))
        self.pushButton_35.setText(_translate("Dialog", "6"))
        self.pushButton_31.setText(_translate("Dialog", "5"))
        self.pushButton_34.setText(_translate("Dialog", "4"))
        self.pushButton_33.setText(_translate("Dialog", "2"))
        self.pushButton_32.setText(_translate("Dialog", "3"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Колич Двиг"))
        self.label_8.setText(_translate("Dialog", "Выберите форму крыла"))
        self.pushButton_42.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "Форма Крыльев"))
        self.label_10.setText(_translate("Dialog", "Выберите форму задних элеронов"))
        self.pushButton_54.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "Вид Задних Элер"))
        self.label_27.setText(_translate("Dialog", "Выберите форму хвоста"))
        self.pushButton_150.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_15), _translate("Dialog", "Вид хвоста"))
        self.label_9.setText(_translate("Dialog", "Какие буквы вы различаете"))
        self.pushButton_48.setWhatsThis(_translate("Dialog", "<html><head/><body><p>1233</p></body></html>"))
        self.pushButton_48.setText(_translate("Dialog", "A"))
        self.pushButton_49.setText(_translate("Dialog", "G"))
        self.pushButton_50.setText(_translate("Dialog", "D"))
        self.pushButton_51.setText(_translate("Dialog", "S"))
        self.pushButton_52.setText(_translate("Dialog", "F"))
        self.pushButton_53.setText(_translate("Dialog", "H"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "Борт Знаки"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

